In [1]:
import numpy as np
import torch
from cogdl.data import Graph
from cogdl.models.nn.gcn import GCN

In [2]:
data_file = np.load("data/DGraph/raw/dgraphfin.npz")

In [3]:
import data_processing

In [4]:
dataset: Graph = data_processing.DGraphDataset()[0]
model = GCN(in_feats=dataset.num_features, hidden_size=64,
            out_feats=2, dropout=0.0, num_layers=2)

In [5]:
model.train()
output = model(dataset)
output

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        ...,
        [0., 0.],
        [0., 0.],
        [0., 0.]], grad_fn=<ScatterAddBackward0>)

In [6]:
output[dataset.val_mask].shape

torch.Size([183862, 2])

In [7]:
dataset.y[dataset.val_mask].shape

torch.Size([183862])

In [8]:
dataset.x

tensor([[ 0.,  5., -1.,  ..., -1., -1., -1.],
        [-1., -1., -1.,  ..., -1., -1., -1.],
        [ 0.,  5., -1.,  ..., -1., -1., -1.],
        ...,
        [-1., -1., -1.,  ..., -1., -1., -1.],
        [-1., -1., -1.,  ..., -1., -1., -1.],
        [-1., -1., -1.,  ..., -1., -1., -1.]])

In [9]:
x = dataset.x
x = (x-x.mean(0))/x.std(0)
dataset.x = x
dataset.x[:5]

tensor([[-0.6881,  0.7298, -0.6371, -0.6409, -0.9152, -0.5998, -0.5686, -0.7932,
         -0.5690, -0.9180, -0.3009, -0.8426, -0.8469, -0.8494, -0.8061, -0.6192,
         -0.6086],
        [-2.0435, -1.5475, -0.6371, -0.6409, -0.9152, -0.5998, -0.5686, -0.7932,
         -0.5690, -0.9180, -0.3009, -0.8426, -0.8469, -0.8494, -0.8061, -0.6192,
         -0.6086],
        [-0.6881,  0.7298, -0.6371, -0.6409, -0.9152, -0.5998, -0.5686, -0.7932,
         -0.5690, -0.9180, -0.3009, -0.8426, -0.8469, -0.8494, -0.8061, -0.6192,
         -0.6086],
        [ 0.6673,  0.7298, -0.6371, -0.6409, -0.9152, -0.5998, -0.5686, -0.7932,
         -0.5690, -0.9180, -0.3009, -0.8426, -0.8469, -0.8494, -0.8061, -0.6192,
         -0.6086],
        [ 0.6673,  1.4890, -0.6371, -0.6409, -0.9152, -0.5998, -0.5686, -0.7932,
         -0.5690, -0.9180, -0.3009, -0.8426, -0.8469, -0.8494, -0.8061, -0.6192,
         -0.6086]])

In [10]:
dataset.y.dim()==2

False

In [16]:
split_idx = {'train':dataset.train_mask, 'valid':dataset.val_mask, 'test':dataset.test_mask}
split_idx['train'].shape[1]

IndexError: tuple index out of range

In [17]:
dataset.x.size(-1), dataset.num_features

(17, 17)